### ISSUE TITLE
sigma → alpha

### ISSUE THREAD

**Issue by lupupu** [phdinds-aim/time_series_handbook#1]
[chapter 5: lorenz attractor](https://phdinds-aim.github.io/time_series_handbook/05_SimplexandSmapProjections/05_Empirical%20Dynamic%20Modelling%20%28Simplex%20and%20SMap_Projections%29.html#lorenz-attractor)
Since formula 8 uses alpha, is it more appropriate to use alpha in the code instead of sigma?

**Comment by franciscorpuz** [comment]
edited the Lorenz equations instead to be consistent with 'sigma'
thanks for catching that lupupu! =)
